"""add username column to user table

Revision ID: 990f9fbb5b57
Revises: 0f1f4b5c2d3e
Create Date: 2026-07-19 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "990f9fbb5b57"
down_revision: Union[str, None] = "0f1f4b5c2d3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("username", sa.String(length=320), nullable=True),
    )
    op.create_unique_constraint(op.f("user_username_key"), "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("user_username_key"), "user", type_="unique")
    op.drop_column("user", "username")
    # ### end Alembic commands ###
