"""Add comments column to IndexerQueryResult table

Revision ID: b2b452fcef23
Revises: 0f1f4b5c2d3e
Create Date: 2026-07-19 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2b452fcef23"
down_revision: Union[str, None] = "0f1f4b5c2d3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "indexer_query_result",
        sa.Column("comments", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer_query_result", "comments")
    # ### end Alembic commands ###
